apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  # Kubernetes will automatically detect the service referenced here by it's name
  # and use its IP address
  database_url: mongodb-service