# For this to work with KIND, you need to configure load balancer.
# See https://kind.sigs.k8s.io/docs/user/loadbalancer/
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  selector:
    app: mongo-express
  # This makes the service external
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30000
